### ISSUE TITLE
Unifying build infrastructure for all manuals

### ISSUE THREAD

**Issue by proofconstruction** [nix-community/projects#6]
The various manuals are currently all built in different ways, and unifying them would provide at least the following improvements:
- Lessening production and maintenance burden on Documentation team
- Increasing docs-coverage of code and approaches being documented

This has been discussed multiple times in Documentation Team meetings, especially following work on https://github.com/NixOS/nixpkgs/pull/237557

**Comment by fricklerhandwerk** [comment]
This is probably an issue for https://github.com/NixOS/nix.dev/
